/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DottedSurfaceDemoRouteImport } from './routes/dotted-surface-demo'
import { Route as IndexRouteImport } from './routes/index'

const DottedSurfaceDemoRoute = DottedSurfaceDemoRouteImport.update({
  id: '/dotted-surface-demo',
  path: '/dotted-surface-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dotted-surface-demo': typeof DottedSurfaceDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dotted-surface-demo': typeof DottedSurfaceDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dotted-surface-demo': typeof DottedSurfaceDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dotted-surface-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dotted-surface-demo'
  id: '__root__' | '/' | '/dotted-surface-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DottedSurfaceDemoRoute: typeof DottedSurfaceDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dotted-surface-demo': {
      id: '/dotted-surface-demo'
      path: '/dotted-surface-demo'
      fullPath: '/dotted-surface-demo'
      preLoaderRoute: typeof DottedSurfaceDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DottedSurfaceDemoRoute: DottedSurfaceDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
